### PR TITLE
Bug fix Attempt Without Permalink

### PR DESCRIPTION
**Pull request by mabardan**
Same thing, without permalink.

### CODE REVIEW

**Comment by narthur** [comment]
It's probably safe to merge this in. You'll probably want to leave "sort" in the frontmatter though. That determines in what order the links appear in navigation. Pages with a lower sort # appear before pages with a higher sort #.

**Comment by mabardan** [comment]
I just did that

**Comment by mabardan** [comment]
Can you merge it so I can see whats happening?

**Comment by narthur** [comment]
Oh, sorry, forgot you can't do that lol

**Comment by narthur** [comment]
You'll need to wait a couple minutes before it's up

**Comment by mabardan** [comment]
Alright

**Comment by mabardan** [comment]
Question, so now is there a way for me to remove the about page UNDER the about oha tab?

**Comment by mabardan** [comment]
Make it somehow not show up in the selection of pages on the side?

**Comment by narthur** [comment]
Is it working? No, at this point there isn't.

**Comment by mabardan** [comment]
Yeah it's working

**Comment by narthur** [comment]
Another possible approach would be to just have all top-level pages redirect to their first child automatically, and then change the system so it doesn't create that "About" link. I think you should make an issue in the issue tracker for that.

**Comment by mabardan** [comment]
alright

**Pull request merged**
